### ISSUE TITLE
AVIF compression not working - module not found

### ISSUE THREAD

**Issue by ScoobyDid** [frostoven/squoosh.frostoven.com#2]
When trying to convert .jpg to .avif, invalid path is being generated:

thread sent an error! undefined:undefined: Cannot find module 'C:\C:\Users\gio\AppData\Roaming\nvm\v16.20.2\node_modules\@frostoven\squoosh-cli\node_modules\@frostoven\libsquoosh\build\avif_node_enc_mt.worker-2a0fdc55.js'

as you may have noticed, the path starts with "C:\C:\"

this bug comes from @squoosh/cli, [issue #1207](https://github.com/GoogleChromeLabs/squoosh/issues/1207) and [issue #1119](https://github.com/GoogleChromeLabs/squoosh/issues/1119); possible solutions are suggested there; this error doesn't occur in @squoosh/cli@0.7.1, but it exists in 0.7.2+ versions

**To Reproduce**
squoosh-cli --avif '{"$quality":40}' ~/Downloads/_images/raw_auto/*.jpg
(instead of /Downloads/_images/raw_auto/*.jpg set path to any folder with .jpg images inside)

**Version:**
OS: Windows 11
node: v16.20.2
npm: v9.8.1

**Comment by aggregate1166877** [comment]
Apologies for the delay in replying, it's been a crazy month and I need to set up a Windows env to test this.

I'll try have a look this week.

**Comment by aggregate1166877** [comment]
There is some deeper problem on Windows. Simply fixing paths to not contain 'C:\C:' does not fix the issue. Instead, the process now hangs after jpg processing starts. Rarely, an error is spat out indicating that `cqLevel` cannot be search for using `in`, so it appears some loop is making bad assumptions somewhere.

I'm not giving on this issue just yet, but I do have pressing deadlines to attend to. I'll resume investigation at a later stage.

**Comment by aggregate1166877** [comment]
@ScoobyDid Avif now works on both Windows and Linux.

The change was not as simple as changing file paths; there were multiple problems with avif, including incorrect parameter assignments and skipped defaults, so I'll leave the task open for a bit in case you experience problems. Let me know if it works for you.

The changes made were not to  `squoosh-cli` directly, but rather to a dependency, so the `squoosh-cli` version number remains the same. Specifically, you may need to purge `libsquoosh` to see the new changes.

**Comment by ScoobyDid** [comment]
@aggregate1166877  

Awesome! I have reinstalled @frostoven/squoosh-cli and tested avif, webp & jpg compression and all works perfectly. 

I have been using @squoosh/cli@0.7.1 as a temp workaround, but now switched back to @frostoven/squoosh-cli. 

Great work, thanks for supporting this package!
