### ISSUE TITLE
Preprocessors options are not used

### ISSUE THREAD

**Issue by raohmaru** [frostoven/squoosh.frostoven.com#3]
Thanks for keeping alive the CLI features of Squoosh!

I found out that when using the preprocessors arguments (`--resize`, `--quant`, `--rotate`) with options (either an Object or a stringified Object), the options are not used in `Image.preprocess()`.

**To Reproduce**
1. Execute the command with the preprocessor option `--quant '{maxNumColors:2}'` or `--quant {maxNumColors:2}`.

**Expected behavior**
The color palette of the image is reduced to 2.

**Actual behavior**
No preprocessor is applied to the image.

**Comment by aggregate1166877** [comment]
@raohmaru Thank you for the contribution!

Fix #4 has been applied in version 0.4.7
