### ISSUE TITLE
Issue when resizing image

### ISSUE THREAD

**Issue by marcosriver** [frostoven/squoosh.frostoven.com#5]
After resizing an image in the web app and copying the CLI command (I have it globally installed) I am getting an error related to resizing the image.

This is the command line:
`squoosh-cli --resize '{"enabled":true,"width":1080,"height":1624,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":75,"target_size":0,"target_PSNR":0,"method":6,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' -d out vertical/001535--003--VK.JPG`

It throws this error:
<img width="1508" alt="image" src="https://github.com/frostoven/Squoosh-with-CLI/assets/48689765/052b1294-5bc4-47fb-b195-f7e2e272cd02">

Without the --resize and it's options works perfectly.

I'm using Node 16.0.0
On a Apple M2 Pro with 16 Ram

Thanks a lot! 
Marcos

**Comment by aggregate1166877** [comment]
Hi @marcosriver

I believe this should now be fixed with PR #4, which has since been published to NPM.

Can you please update your packages and try again?

**Comment by aggregate1166877** [comment]
This appears to be working now; closing. Please let me know if the issue persists.
