### ISSUE TITLE
Squoosh CLI doesn't work on Node v20 (ERR_INVALID_URL)

### ISSUE THREAD

**Issue by popcar2** [frostoven/squoosh.frostoven.com#7]
Thanks for making this, it's *really* useful to have a working squoosh cli!

**Describe the bug**
The newest stable version of Node gives me an error when trying to use squoosh-cli. Downgrading to Node v16 makes it work normally. 

**To Reproduce**
1. Upgrade to the latest Node version (v20.11.1)
2. Attempt to use any squoosh-cli command
3. Watch it fail

**Version:**
 - OS w/ version: Nobara Linux 39
 - Node version: 20.11.1
 - npm version: 10.2.4

**Additional context, screenshots, screencasts**

![image](https://github.com/frostoven/Squoosh-with-CLI/assets/16920817/e70ccf3a-4ef0-4e82-b916-03f8b0be1295)

![image](https://github.com/frostoven/Squoosh-with-CLI/assets/16920817/3d738de0-ed39-4a8e-b2e2-53c626315107)

**Comment by aggregate1166877** [comment]
Thanks for the report. We currently have some tight deadlines so development on this repo has been paused for a while, I'll try get to this in the next few weeks.

**Comment by uhlhosting** [comment]
```
> squoosh-cli
/usr/local/lib/node_modules/@frostoven/squoosh-cli/node_modules/@frostoven/libsquoosh/build/index.js:30
globalThis.navigator={hardwareConcurrency:os.cpus().length};const pngEncDecPromise=init$2(require$$1.promises.readFile(pathify(pngEncDecWasm)));const oxipngPromise=init$1(require$$1.promises.readFile(pathify(oxipngWasm)));const resizePromise=init(require$$1.promises.readFile(pathify(resizeWasm)));const imageQuantPromise=instantiateEmscriptenWasm(Module$1,imageQuantWasm);globalThis.ImageData=ImageData$1;function resizeNameToIndex(name){switch(name){case"triangle":return 0;case"catrom":return 1;case"mitchell":return 2;case"lanczos3":return 3;default:throw Error(`Unknown resize algorithm "${name}"`)}}function resizeWithAspect({input_width,input_height,target_width,target_height}){if(!target_width&&!target_height){throw Error("Need to specify at least width or height when resizing")}if(target_width&&target_height){return{width:target_width,height:target_height}}if(!target_width){return{width:Math.round(input_width/input_height*target_height),height:target_height}}return{width:target_width,height:Math.round(input_height/input_width*target_width)}}const preprocessors={resize:{name:"Resize",description:"Resize the image before compressing",instantiate:async()=>{await resizePromise;return(buffer,input_width,input_height,{width,height,method,premultiply,linearRGB})=>{({width,height}=resizeWithAspect({input_width,input_height,target_width:width,target_height:height}));return new ImageData$1(resize(buffer,input_width,input_height,width,height,resizeNameToIndex(method),premultiply,linearRGB),width,height)}},defaultOptions:{method:"lanczos3",fitMethod:"stretch",premultiply:true,linearRGB:true}},// // TODO: Need to handle SVGs and HQX
                    ^

TypeError: Cannot set property navigator of #<Object> which has only a getter
    at Object.<anonymous> (/usr/local/lib/node_modules/@frostoven/squoosh-cli/node_modules/@frostoven/libsquoosh/build/index.js:30:21)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at cjsLoader (node:internal/modules/esm/translators:344:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:284:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5)

Node.js v22.0.0
```
same here

**Comment by aggregate1166877** [comment]
Hi @popcar2  and @uhlhosting - I believe this issue is now fixed. Can you please test on your respective platforms?

In the now-live version of this package (CLI `v0.8.1` and libSquoosh `v0.4.8`) the issue is no longer present for Node versions 16, 18, 20, and 22 on Ubuntu Linux. I also tested Node 20 on Windows 10 via Git Bash.

#### Info
This bug started happening because Node has included an experimental [native fetch](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) as of Node 18.

For now I'm disabling this by passing `--no-experimental-fetch` via the the CLI scripts. I suspect this will break again in the (hopefully far) future, but I'd rather not make decisions now based on how Node *might* evolve. We'll deal with this as needed if the issue recurs.

**Comment by popcar2** [comment]
I can confirm it works on the latest Node stable version (`node-v20.12.2`). Thank you for fixing it!

**Comment by aggregate1166877** [comment]
> I can confirm it works on the latest Node stable version (`node-v20.12.2`). Thank you for fixing it!

No problem :)
